/*
 * THIS FILE WAS AUTOMATICALLY GENERATED, DO NOT EDIT.
 *
 * This file was generated by the dom/make_names.pl script.
 *
 * Copyright (C) 2005, 2006, 2007, 2008, 2009, 2013 Apple Inc.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE INC. ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE INC. OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include "config.h"
#include "JSMathMLElementWrapperFactory.h"


#if ENABLE(MATHML)

#include "JSMathMLAnnotationElement.h"
#include "JSMathMLSelectElement.h"
#include "JSMathMLMathElement.h"
#include "JSMathMLMencloseElement.h"
#include "JSMathMLRowElement.h"
#include "JSMathMLFractionElement.h"
#include "JSMathMLTokenElement.h"
#include "JSMathMLScriptsElement.h"
#include "JSMathMLOperatorElement.h"
#include "JSMathMLUnderOverElement.h"
#include "JSMathMLPaddedElement.h"
#include "JSMathMLPresentationElement.h"
#include "JSMathMLSpaceElement.h"
#include "JSMathMLElement.h"
#include "MathMLAnnotationElement.h"
#include "MathMLSelectElement.h"
#include "MathMLElement.h"
#include "MathMLMathElement.h"
#include "MathMLMencloseElement.h"
#include "MathMLRowElement.h"
#include "MathMLFractionElement.h"
#include "MathMLTokenElement.h"
#include "MathMLScriptsElement.h"
#include "MathMLOperatorElement.h"
#include "MathMLUnderOverElement.h"
#include "MathMLPaddedElement.h"
#include "MathMLPresentationElement.h"
#include "MathMLSpaceElement.h"
#include "MathMLElement.h"

#include "MathMLNames.h"

#include "Document.h"
#include "RuntimeEnabledFeatures.h"
#include "Settings.h"
#include <wtf/NeverDestroyed.h>
#include <wtf/StdLibExtras.h>

using namespace JSC;

namespace WebCore {

using namespace MathMLNames;

typedef JSDOMObject* (*CreateMathMLElementWrapperFunction)(JSDOMGlobalObject*, Ref<MathMLElement>&&);

static JSDOMObject* createMathMLAnnotationElementWrapper(JSDOMGlobalObject* globalObject, Ref<MathMLElement>&& element)
{
    return CREATE_DOM_WRAPPER(globalObject, MathMLAnnotationElement, WTFMove(element));
}

static JSDOMObject* createMathMLSelectElementWrapper(JSDOMGlobalObject* globalObject, Ref<MathMLElement>&& element)
{
    return CREATE_DOM_WRAPPER(globalObject, MathMLSelectElement, WTFMove(element));
}

static JSDOMObject* createMathMLMathElementWrapper(JSDOMGlobalObject* globalObject, Ref<MathMLElement>&& element)
{
    return CREATE_DOM_WRAPPER(globalObject, MathMLMathElement, WTFMove(element));
}

static JSDOMObject* createMathMLMencloseElementWrapper(JSDOMGlobalObject* globalObject, Ref<MathMLElement>&& element)
{
    return CREATE_DOM_WRAPPER(globalObject, MathMLMencloseElement, WTFMove(element));
}

static JSDOMObject* createMathMLRowElementWrapper(JSDOMGlobalObject* globalObject, Ref<MathMLElement>&& element)
{
    return CREATE_DOM_WRAPPER(globalObject, MathMLRowElement, WTFMove(element));
}

static JSDOMObject* createMathMLFractionElementWrapper(JSDOMGlobalObject* globalObject, Ref<MathMLElement>&& element)
{
    return CREATE_DOM_WRAPPER(globalObject, MathMLFractionElement, WTFMove(element));
}

static JSDOMObject* createMathMLTokenElementWrapper(JSDOMGlobalObject* globalObject, Ref<MathMLElement>&& element)
{
    return CREATE_DOM_WRAPPER(globalObject, MathMLTokenElement, WTFMove(element));
}

static JSDOMObject* createMathMLScriptsElementWrapper(JSDOMGlobalObject* globalObject, Ref<MathMLElement>&& element)
{
    return CREATE_DOM_WRAPPER(globalObject, MathMLScriptsElement, WTFMove(element));
}

static JSDOMObject* createMathMLOperatorElementWrapper(JSDOMGlobalObject* globalObject, Ref<MathMLElement>&& element)
{
    return CREATE_DOM_WRAPPER(globalObject, MathMLOperatorElement, WTFMove(element));
}

static JSDOMObject* createMathMLUnderOverElementWrapper(JSDOMGlobalObject* globalObject, Ref<MathMLElement>&& element)
{
    return CREATE_DOM_WRAPPER(globalObject, MathMLUnderOverElement, WTFMove(element));
}

static JSDOMObject* createMathMLPaddedElementWrapper(JSDOMGlobalObject* globalObject, Ref<MathMLElement>&& element)
{
    return CREATE_DOM_WRAPPER(globalObject, MathMLPaddedElement, WTFMove(element));
}

static JSDOMObject* createMathMLPresentationElementWrapper(JSDOMGlobalObject* globalObject, Ref<MathMLElement>&& element)
{
    return CREATE_DOM_WRAPPER(globalObject, MathMLPresentationElement, WTFMove(element));
}

static JSDOMObject* createMathMLSpaceElementWrapper(JSDOMGlobalObject* globalObject, Ref<MathMLElement>&& element)
{
    return CREATE_DOM_WRAPPER(globalObject, MathMLSpaceElement, WTFMove(element));
}


static NEVER_INLINE void populateMathMLWrapperMap(HashMap<AtomicStringImpl*, CreateMathMLElementWrapperFunction>& map)
{
    struct TableEntry {
        const QualifiedName& name;
        CreateMathMLElementWrapperFunction function;
    };

    static const TableEntry table[] = {
        { annotationTag, createMathMLAnnotationElementWrapper },
        { annotation_xmlTag, createMathMLAnnotationElementWrapper },
        { mactionTag, createMathMLSelectElementWrapper },
        { mathTag, createMathMLMathElementWrapper },
        { mencloseTag, createMathMLMencloseElementWrapper },
        { merrorTag, createMathMLRowElementWrapper },
        { mfencedTag, createMathMLRowElementWrapper },
        { mfracTag, createMathMLFractionElementWrapper },
        { miTag, createMathMLTokenElementWrapper },
        { mmultiscriptsTag, createMathMLScriptsElementWrapper },
        { mnTag, createMathMLTokenElementWrapper },
        { moTag, createMathMLOperatorElementWrapper },
        { moverTag, createMathMLUnderOverElementWrapper },
        { mpaddedTag, createMathMLPaddedElementWrapper },
        { mphantomTag, createMathMLRowElementWrapper },
        { mprescriptsTag, createMathMLPresentationElementWrapper },
        { mrootTag, createMathMLRowElementWrapper },
        { mrowTag, createMathMLRowElementWrapper },
        { msTag, createMathMLTokenElementWrapper },
        { mspaceTag, createMathMLSpaceElementWrapper },
        { msqrtTag, createMathMLRowElementWrapper },
        { mstyleTag, createMathMLRowElementWrapper },
        { msubTag, createMathMLScriptsElementWrapper },
        { msubsupTag, createMathMLScriptsElementWrapper },
        { msupTag, createMathMLScriptsElementWrapper },
        { mtableTag, createMathMLPresentationElementWrapper },
        { mtextTag, createMathMLTokenElementWrapper },
        { munderTag, createMathMLUnderOverElementWrapper },
        { munderoverTag, createMathMLUnderOverElementWrapper },
        { noneTag, createMathMLPresentationElementWrapper },
        { semanticsTag, createMathMLSelectElementWrapper },
    };

    for (unsigned i = 0; i < WTF_ARRAY_LENGTH(table); ++i)
        map.add(table[i].name.localName().impl(), table[i].function);
}

JSDOMObject* createJSMathMLWrapper(JSDOMGlobalObject* globalObject, Ref<MathMLElement>&& element)
{
    static NeverDestroyed<HashMap<AtomicStringImpl*, CreateMathMLElementWrapperFunction>> functions;
    if (functions.get().isEmpty())
        populateMathMLWrapperMap(functions);
    if (auto function = functions.get().get(element->localName().impl()))
        return function(globalObject, WTFMove(element));
    return CREATE_DOM_WRAPPER(globalObject, MathMLElement, WTFMove(element));
}

}

#endif
