[
] partial interface Navigator { 
    [CallWith=ScriptExecutionContext, RaisesException] boolean sendBeacon(DOMString url, [Default=Undefined] Blob? data);
    [CallWith=ScriptExecutionContext, RaisesException] boolean sendBeacon(DOMString url, [Default=Undefined] ArrayBufferView? data);
    [CallWith=ScriptExecutionContext, RaisesException] boolean sendBeacon(DOMString url, [Default=Undefined] DOMFormData? data);
    [CallWith=ScriptExecutionContext, RaisesException] boolean sendBeacon(DOMString url, [Default=NullString] DOMString? data);
}; 
