[
] partial interface Navigator {
    [CallWith=ScriptExecutionContext, MayThrowLegacyException] boolean sendBeacon(DOMString url, [Default=Undefined] Blob? data);
    [CallWith=ScriptExecutionContext, MayThrowLegacyException] boolean sendBeacon(DOMString url, [Default=Undefined] ArrayBufferView? data);
    [CallWith=ScriptExecutionContext, MayThrowLegacyException] boolean sendBeacon(DOMString url, [Default=Undefined] DOMFormData? data);
    [CallWith=ScriptExecutionContext, MayThrowLegacyException] boolean sendBeacon(DOMString url, [Default=NullString] DOMString? data);
};
