# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


SET(CPACK_BINARY_7Z "")
SET(CPACK_BINARY_BUNDLE "")
SET(CPACK_BINARY_CYGWIN "")
SET(CPACK_BINARY_DEB "OFF")
SET(CPACK_BINARY_DRAGNDROP "")
SET(CPACK_BINARY_IFW "OFF")
SET(CPACK_BINARY_NSIS "OFF")
SET(CPACK_BINARY_OSXX11 "")
SET(CPACK_BINARY_PACKAGEMAKER "")
SET(CPACK_BINARY_RPM "OFF")
SET(CPACK_BINARY_STGZ "ON")
SET(CPACK_BINARY_TBZ2 "OFF")
SET(CPACK_BINARY_TGZ "ON")
SET(CPACK_BINARY_TXZ "OFF")
SET(CPACK_BINARY_TZ "ON")
SET(CPACK_BINARY_WIX "")
SET(CPACK_BINARY_ZIP "")
SET(CPACK_CMAKE_GENERATOR "Ninja")
SET(CPACK_COMPONENTS_ALL "")
SET(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
SET(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
SET(CPACK_GENERATOR "STGZ;TGZ;TZ")
SET(CPACK_INSTALL_CMAKE_PROJECTS "/home/naveen/workspace/ML_03/buildroot-wpe/output/build/wpe-9d4c9c472778d89386fa3533f95f6b8e8c203894/build-Release;WebKit;ALL;/")
SET(CPACK_INSTALL_PREFIX "/usr")
SET(CPACK_MODULE_PATH "/home/naveen/workspace/ML_03/buildroot-wpe/output/build/wpe-9d4c9c472778d89386fa3533f95f6b8e8c203894/Source/cmake")
SET(CPACK_NSIS_DISPLAY_NAME "WebKit-WPE 0.1.1")
SET(CPACK_NSIS_INSTALLER_ICON_CODE "")
SET(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
SET(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
SET(CPACK_NSIS_PACKAGE_NAME "WebKit-WPE 0.1.1")
SET(CPACK_OUTPUT_CONFIG_FILE "/home/naveen/workspace/ML_03/buildroot-wpe/output/build/wpe-9d4c9c472778d89386fa3533f95f6b8e8c203894/build-Release/CPackConfig.cmake")
SET(CPACK_PACKAGE_DEFAULT_LOCATION "/")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "/home/naveen/workspace/ML_03/buildroot-wpe/output/host/usr/share/cmake-3.5/Templates/CPack.GenericDescription.txt")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "WebKit built using CMake")
SET(CPACK_PACKAGE_FILE_NAME "WebKit-WPE-0.1.1-Linux")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "WebKit-WPE 0.1.1")
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "WebKit-WPE 0.1.1")
SET(CPACK_PACKAGE_NAME "WebKit-WPE")
SET(CPACK_PACKAGE_RELOCATABLE "true")
SET(CPACK_PACKAGE_VENDOR "Humanity")
SET(CPACK_PACKAGE_VERSION "0.1.1")
SET(CPACK_PACKAGE_VERSION_MAJOR "0")
SET(CPACK_PACKAGE_VERSION_MINOR "1")
SET(CPACK_PACKAGE_VERSION_PATCH "1")
SET(CPACK_RESOURCE_FILE_LICENSE "/home/naveen/workspace/ML_03/buildroot-wpe/output/host/usr/share/cmake-3.5/Templates/CPack.GenericLicense.txt")
SET(CPACK_RESOURCE_FILE_README "/home/naveen/workspace/ML_03/buildroot-wpe/output/host/usr/share/cmake-3.5/Templates/CPack.GenericDescription.txt")
SET(CPACK_RESOURCE_FILE_WELCOME "/home/naveen/workspace/ML_03/buildroot-wpe/output/host/usr/share/cmake-3.5/Templates/CPack.GenericWelcome.txt")
SET(CPACK_SET_DESTDIR "OFF")
SET(CPACK_SOURCE_7Z "")
SET(CPACK_SOURCE_CYGWIN "")
SET(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
SET(CPACK_SOURCE_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp$;\\.#;/#;/\\.gitignore$;/\\.gitattributes$;/PerformanceTests/;/Examples/;/Websites/;\\.mk$;\\.make$;Makefile;\\.xcodeproj;\\.xcconfig;\\.gyp;\\.pri$;\\.pro$;~$;\\.mode;\\.pbxuser$;\\.perspective;\\.pyc$;\\.pyo$;/cmake-build/;/build/;/WebKitBuild/;/Tools/Scripts/webkitpy/thirdparty/autoinstalled/;/LayoutTests/;/ManualTests/;/tests/;/Tools/;/manual-tools/;/tools/;/PageLoadTools/;/carbon/;/Carbon/;carbon\\.;Carbon\\.;/cf/;/Cf/;cf\\.;Cf\\.;/cg/;/Cg/;cg\\.;Cg\\.;/chromium/;/Chromium/;chromium\\.;Chromium\\.;/cocoa/;/Cocoa/;cocoa\\.;Cocoa\\.;/Configurations/;/Configurations/;Configurations\\.;Configurations\\.;/curl/;/Curl/;curl\\.;Curl\\.;/gstreamer/;/Gstreamer/;gstreamer\\.;Gstreamer\\.;/gtk/;/Gtk/;gtk\\.;Gtk\\.;/iphone/;/Iphone/;iphone\\.;Iphone\\.;/mac/;/Mac/;mac\\.;Mac\\.;/opentype/;/Opentype/;opentype\\.;Opentype\\.;/openvg/;/Openvg/;openvg\\.;Openvg\\.;/qscriptengine/;/Qscriptengine/;qscriptengine\\.;Qscriptengine\\.;/qscriptstring/;/Qscriptstring/;qscriptstring\\.;Qscriptstring\\.;/qscriptvalue/;/Qscriptvalue/;qscriptvalue\\.;Qscriptvalue\\.;/qt/;/Qt/;qt\\.;Qt\\.;/qt4/;/Qt4/;qt4\\.;Qt4\\.;/win/;/Win/;win\\.;Win\\.;/wxcode/;/Wxcode/;wxcode\\.;Wxcode\\.;/WebKitLibraries/;/English\\.lproj/;/Source/WebKit2/;\\.a$;\\.exe$;\\.mm$;/cairo/;/Cairo/;cairo\\.;Cairo\\.;/efl/;/Efl/;efl\\.;Efl\\.;/glib/;/Glib/;glib\\.;Glib\\.;/gobject/;/Gobject/;gobject\\.;Gobject\\.;/icu/;/Icu/;icu\\.;Icu\\.;/posix/;/Posix/;posix\\.;Posix\\.;/soup/;/Soup/;soup\\.;Soup\\.")
SET(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/naveen/workspace/ML_03/buildroot-wpe/output/build/wpe-9d4c9c472778d89386fa3533f95f6b8e8c203894/build-Release/CPackSourceConfig.cmake")
SET(CPACK_SOURCE_TBZ2 "ON")
SET(CPACK_SOURCE_TGZ "ON")
SET(CPACK_SOURCE_TXZ "ON")
SET(CPACK_SOURCE_TZ "ON")
SET(CPACK_SOURCE_ZIP "OFF")
SET(CPACK_SYSTEM_NAME "Linux")
SET(CPACK_TOPLEVEL_TAG "Linux")
SET(CPACK_WIX_SIZEOF_VOID_P "4")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/naveen/workspace/ML_03/buildroot-wpe/output/build/wpe-9d4c9c472778d89386fa3533f95f6b8e8c203894/build-Release/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
